//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastSearcher81.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastSearcher81.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app...
        ///Please offer me a coffee!.
        /// </summary>
        public static string Ad1 {
            get {
                return ResourceManager.GetString("Ad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to read an Italian book? 
        ///Try SCEGLI ME by Giulia Cacciatore!.
        /// </summary>
        public static string Ad2 {
            get {
                return ResourceManager.GetString("Ad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Searcher is now available also for your notebook!.
        /// </summary>
        public static string Ad3 {
            get {
                return ResourceManager.GetString("Ad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All engines.
        /// </summary>
        public static string AllEngines {
            get {
                return ResourceManager.GetString("AllEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aggiungi.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppBarButtonTextInfo {
            get {
                return ResourceManager.GetString("AppBarButtonTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        public static string AppBarButtonTextMicrophone {
            get {
                return ResourceManager.GetString("AppBarButtonTextMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string AppBarButtonTextPinToStart {
            get {
                return ResourceManager.GetString("AppBarButtonTextPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce di menu.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Searcher 8.1.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application does not track the activities of the users. 
        ///The application is not connected to the companies that are possible to use in it. All the trademarks quoted in the app are of property of the right possessor, who can ask for the removal or the modification of their mark whenever they want, just writing an email to the address present in the box “contact us”. 
        ///To suggest the insertion of a new engine, please send an email to the address present in the box “contact us”..
        /// </summary>
        public static string DisclaimerMessage {
            get {
                return ResourceManager.GetString("DisclaimerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when loading the app, please reboot.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string InfoHeader {
            get {
                return ResourceManager.GetString("InfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2015 - 2016 by Luca Mollo, LMESoft
        ///Author: Luca Mollo
        ///Translator: Giulia Cacciatore.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images.
        /// </summary>
        public static string PickerImage {
            get {
                return ResourceManager.GetString("PickerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on web.
        /// </summary>
        public static string PickerWeb {
            get {
                return ResourceManager.GetString("PickerWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch your app to make changes effective..
        /// </summary>
        public static string RebootMessageForLanguageEn {
            get {
                return ResourceManager.GetString("RebootMessageForLanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar la aplicación para actuar las modificaciones..
        /// </summary>
        public static string RebootMessageForLanguageEs {
            get {
                return ResourceManager.GetString("RebootMessageForLanguageEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavvia l&apos;applicazione per rendere effettivo il cambiamento..
        /// </summary>
        public static string RebootMessageForLanguageIt {
            get {
                return ResourceManager.GetString("RebootMessageForLanguageIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed.
        /// </summary>
        public static string RebootMessageHeaderForLanguageEn {
            get {
                return ResourceManager.GetString("RebootMessageHeaderForLanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma modificado.
        /// </summary>
        public static string RebootMessageHeaderForLanguageEs {
            get {
                return ResourceManager.GetString("RebootMessageHeaderForLanguageEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua cambiata.
        /// </summary>
        public static string RebootMessageHeaderForLanguageIt {
            get {
                return ResourceManager.GetString("RebootMessageHeaderForLanguageIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search image with.
        /// </summary>
        public static string SearchImage {
            get {
                return ResourceManager.GetString("SearchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websearch with.
        /// </summary>
        public static string SearchWeb {
            get {
                return ResourceManager.GetString("SearchWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please retry; if the problem endure contact the developer..
        /// </summary>
        public static string SpeechError {
            get {
                return ResourceManager.GetString("SpeechError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want me to search?.
        /// </summary>
        public static string SpeechExampleText {
            get {
                return ResourceManager.GetString("SpeechExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        public static string SpeechListenText {
            get {
                return ResourceManager.GetString("SpeechListenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate us.
        /// </summary>
        public static string ValutationText {
            get {
                return ResourceManager.GetString("ValutationText", resourceCulture);
            }
        }
    }
}
